services:
  python:
    restart: always
    build: ./python
    depends_on:
     - db
    ports:
     - "5000:5000"
    environment:
      MYSQL_ROOT_PASSOWRD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3307
    
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DB: blockchain
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
     - "3307:3307"
    expose:
     - 3307
volumes:
  db_data: